### ISSUE TITLE
Improving SVG Parsing

### ISSUE THREAD

**Issue by adastier** [fabricjs/fabric.js#1055]
Hi! I keep hitting issues with SVG parsing, so figured I would do a summary of the information I gathered on the bugs in the SVG parser. I am reviewing the code, but that will not be enough, I think...
Multiple issues have been opened about svg parsing bugs, and a few of them are pretty similar.

So here is a quick recap of what I found so far :
- [X] Issue with [nested transformations](http://www.w3.org/TR/SVG11/coords.html#NestedTransformations) :

The example on the W3C page is not rendered correctly (imported in kitchensink). A lot of .svg I use, created with Adobe Illustrator or Inkscape, were not correctly rendered if a group contained a transform matrix (while being correctly rendered in Chrome/IE/Firefox).

I think this is related to <del>#562</del> ( "Inspecting the parsed object from the SVG string showed that the transform matrix only accounted for the transform applied to the `<path>` and not the `<g>`."), <del>#705</del> , <del>#975</del>, <del>#474</del> , <del>#567</del> , #502 , <del>#905</del> , <del>#975</del> (here I think the SVG output is correct, but the SVG is not parsed correctly when re-parsing), <del>#384</del> , <del>#443</del> , <del>#917</del> , <del>#1023</del> , #1280 
- [X] Issue with transform and text element (if in `<g>` ? not in `<g>` ?)

As seen in issues <del>#547</del> , <del>#974</del> ,  <del>#1023</del>
- [ ] `<tspan>` is not supported (known, of course)

As seen in #420 , #502 , <del>#384</del> ,  #1280 
- [x] Issue that renders weird paths 

Part of it was because of numbers that have the form 1.11111e-5 and was fixed. Why other files seem to fail is the same way remains an open question.
As seen in <del>#961</del> (now fixed) , ( <del>#1021</del> was fixed, the issue was with fill-rule="evenodd") 
- [ ] Issue with feColorMatrix and possibly more filters & masks as seen in #1096 (see [the w3 website for details about them](http://www.w3.org/TR/SVG/filters.html))
- [x] "visibility: hidden" style property ignored in some cases : #1280
- [ ] glyph is not supported #1290
- [x] No support for `<use>` <del>#1305</del>

I figured having a place to check them all could be useful. I hope this will help some of you. I'll try to update as I continue to investigate the issue. Please feel free to contribute if I missed some issues or if you have any idea/comment !

_Most fiddles in the referenced issues will not work because they use the old all.js reference. For them to work, the Externel Resource all.js must be replaced with https://rawgithub.com/kangax/fabric.js/master/dist/fabric.js_
##

**Comment by canvaskisa** [comment]
Hey, guys, I've got som eproblem with svg parsing here: http://stackoverflow.com/questions/28364546/fabricjs-svg-parsing-error
If you have any ideas, how to improve this stuff i'll aprecciate that very much.

**Comment by asturur** [comment]
hey @canvaskisa i just replied you on SO to use latest version. please accept answer so people see before asking anything to trynat least kitchensink demo. regards

**Comment by canvaskisa** [comment]
@asturur, weird, i'm using npm version "fabric": "^1.4.13"

**Comment by asturur** [comment]
but on kitchensink renders good. so please pull from the website itself, maybe kangax updated the dist folder but did not release the 1.4.14
would you mind to try to pull the latest and try?

**Comment by canvaskisa** [comment]
@asturur, i tried the last version from site, and everything is fine, seems like it's an old version of fabric in npm. thanks for help, man

**Comment by asturur** [comment]
please, even if my answer is incorrect in this case, just mark it, testing
kitchensink is something people are not doing, and they just open issues
here or in SO.

if you do not mind of course.
Il 09/feb/2015 11:26 "aleksandr" <notifications@github.com> ha scritto:

**Comment by shahafan** [comment]
#6023 
@asturur I've opened a pr fixing a lot of svg parsing errors I've seen here.. way too much for giving examples.
Took it from svgo package.. see if that works for you.

**Comment by curvedriver** [comment]
Hi,
I found some issues while parsing a SVG which contains other nested SVG elements. The positions and the sizes of the inner SVG elements are not correct. 

Is that already considered by one of the existing tasks?

I created a fiddle for that: 
https://jsfiddle.net/curvedriver/qjouaxgs/15/

The browsers native svg visualization (chrome: Version 79.0.3945.117) looks as expected.
![image](https://user-images.githubusercontent.com/54622444/72346627-aa858600-36d6-11ea-8d02-eec3acd59436.png)

**Comment by asturur** [comment]
no is not, would be nice if you open its own issue with that. thanks.

**Comment by curvedriver** [comment]
Thanks @asturur!
Done -> https://github.com/fabricjs/fabric.js/issues/6105
