### ISSUE TITLE
A fabric-based graphics editor applies mitu-editor👋

### ISSUE THREAD

**Issue by MrXujiang** [fabricjs/fabric.js#7450]
Thank you very much for fabric, I developed a graphics editor mitu based on it, hoping it will help fabric make the community stronger.
<img alt="License: MIT" src="http://cdn.dooring.cn/dr/mitu.png" />

[mitu-fabric](https://github.com/H5-Dooring/mitu-editor)

### Features
- [x] The underlying graphics component
- [x] Component controller, support for deletion, control handle, rotation, element multi-select
- [x] Save the picture
- [x] Save the picture template
- [x] Graphic property editor
- [x] Canvas control
- [x] Template list, one-click import footage template
- [x] Empty the canvas
- [x] Live preview
- [x] Color reader

### Todo
- [ ] Undo redoing
- [x] Canvas background settings
- [x] Enrich the graphics component library
- [x] Modular interface
- [x] Resolve PSD
